### ISSUE TITLE
Routes required

### ISSUE THREAD

**Issue by K-Kumar-01** [Atul-tyagi23/CSO-Project#2]
### Following routes are required

base_url is http://localhot:PORT/api

### Categories routes
/categories - to get all categories
/categories/edit/:id - to edit a category(maybe we will not require it)
/categories/delte- to delete a category(maybe we wont require)

### For users
/users- fetch list of all users
/user/signup - signup a user
/user/login - login a user
/user/:(id/username) - fetch user by either id or username, you can decide
/user/:(id/username)/edit - edit a users's detail
/user/:(id/username)/delete - delete a user

**Comment by Atul-tyagi23** [comment]
Added routes for login and signup for users
