### ISSUE TITLE
Adding default images for categories

### ISSUE THREAD

**Issue by K-Kumar-01** [Atul-tyagi23/CSO-Project#3]
Create a new folder and add default image for categories
example For technology you can choose a laptop image
# How to do it:
Clone the repo create a new folder in it called defaultImages
save the image as the category name
*Example* for _technology_ save the image as technology.jpg
Try to find the image with transparent background and in jpg or png format only.
once done comment in the issue

**Comment by K-Kumar-01** [comment]
You need to do the work before you can close the issue

**Comment by ArcoRATH** [comment]
Done
